CREATE TABLE event_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_event_types PRIMARY KEY (id)
);

CREATE TABLE events
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_type_id    BIGINT                                  NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    description      VARCHAR(255),
    max_participants INTEGER,
    privacy_type     SMALLINT                                NOT NULL,
    start_date       date                                    NOT NULL,
    end_date         date                                    NOT NULL,
    start_time       time WITHOUT TIME ZONE                  NOT NULL,
    end_time         time WITHOUT TIME ZONE                  NOT NULL,
    country          VARCHAR(255),
    city             VARCHAR(255),
    address          VARCHAR(255),
    latitude         BIGINT,
    longitude        BIGINT,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_EVENTTYPE FOREIGN KEY (event_type_id) REFERENCES event_types (id);