CREATE TABLE event_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_eventtype PRIMARY KEY (id)
);

CREATE TABLE offering_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_offeringtype PRIMARY KEY (id)
);

CREATE TABLE service
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(255),
    description           VARCHAR(255),
    price                 DOUBLE PRECISION                        NOT NULL,
    discount              DOUBLE PRECISION                        NOT NULL,
    is_visible            BOOLEAN                                 NOT NULL,
    is_available          BOOLEAN                                 NOT NULL,
    offering_type         SMALLINT,
    specifics             VARCHAR(255),
    duration              INTEGER                                 NOT NULL,
    reservation_deadline  INTEGER                                 NOT NULL,
    cancellation_deadline INTEGER                                 NOT NULL,
    reservation_type      VARCHAR(255),
    CONSTRAINT pk_service PRIMARY KEY (id)
);

CREATE TABLE service_images
(
    service_id BIGINT NOT NULL,
    images_url VARCHAR(255)
);

ALTER TABLE service_images
    ADD CONSTRAINT fk_service_images_on_service FOREIGN KEY (service_id) REFERENCES service (id);