ALTER TABLE event_invitation
DROP
CONSTRAINT fk_eventinvitation_on_event;

CREATE TABLE event_invitations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    guest_email     VARCHAR(255),
    invitation_code VARCHAR(255)                            NOT NULL,
    status          VARCHAR(255)                            NOT NULL,
    event_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_event_invitations PRIMARY KEY (id)
);

ALTER TABLE event_invitations
    ADD CONSTRAINT uc_event_invitations_invitationcode UNIQUE (invitation_code);

ALTER TABLE event_invitations
    ADD CONSTRAINT FK_EVENT_INVITATIONS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

DROP TABLE event_invitation CASCADE;