ALTER TABLE public.notification
DROP CONSTRAINT notification_notification_category_check;

DROP TABLE  notification;

CREATE TABLE notification
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                 VARCHAR(255)                            NOT NULL,
    message               VARCHAR(255)                            NOT NULL,
    is_viewed             BOOLEAN                                 NOT NULL,
    entity_id             BIGINT                                  NOT NULL,
    notification_category SMALLINT                                NOT NULL,
    user_id               BIGINT,
    created_date          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_notification PRIMARY KEY (id)
);

ALTER TABLE notification
    ADD CONSTRAINT FK_NOTIFICATION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);