CREATE TABLE budget_item
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    offering_category_type VARCHAR(255),
    event_id               BIGINT                                  NOT NULL,
    amount                 DOUBLE PRECISION                        NOT NULL,
    currency               VARCHAR(255),
    CONSTRAINT pk_budgetitem PRIMARY KEY (id)
);

CREATE TABLE event_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    name        VARCHAR(255)                            NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_event_types PRIMARY KEY (id)
);

CREATE TABLE events
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_type_id    BIGINT                                  NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    description      VARCHAR(255),
    max_participants INTEGER,
    privacy_type     SMALLINT                                NOT NULL,
    start_date       date                                    NOT NULL,
    end_date         date                                    NOT NULL,
    start_time       time WITHOUT TIME ZONE                  NOT NULL,
    end_time         time WITHOUT TIME ZONE                  NOT NULL,
    created_date     TIMESTAMP WITHOUT TIME ZONE,
    country          VARCHAR(255),
    city             VARCHAR(255),
    address          VARCHAR(255),
    latitude         BIGINT,
    longitude        BIGINT,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE favorite_products
(
    favorite_products_id BIGINT NOT NULL,
    users_id             BIGINT NOT NULL
);

CREATE TABLE favorite_services
(
    favorite_services_id BIGINT NOT NULL,
    users_id             BIGINT NOT NULL
);

CREATE TABLE offering_review
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment     VARCHAR(255)                            NOT NULL,
    status      VARCHAR(255),
    purchase_id BIGINT,
    CONSTRAINT pk_offeringreview PRIMARY KEY (id)
);

CREATE TABLE offering_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    status      VARCHAR(255),
    CONSTRAINT pk_offeringtype PRIMARY KEY (id)
);

CREATE TABLE product
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 VARCHAR(255)                            NOT NULL,
    description          VARCHAR(255),
    price                DOUBLE PRECISION                        NOT NULL,
    discount             DOUBLE PRECISION                        NOT NULL,
    is_visible           BOOLEAN                                 NOT NULL,
    is_available         BOOLEAN                                 NOT NULL,
    status               SMALLINT,
    offering_category_id BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE product_event_type
(
    product_id    BIGINT NOT NULL,
    event_type_id BIGINT NOT NULL
);

CREATE TABLE purchase
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date date                                    NOT NULL,
    start_time time WITHOUT TIME ZONE                  NOT NULL,
    end_date   date                                    NOT NULL,
    end_time   time WITHOUT TIME ZONE                  NOT NULL,
    event_id   BIGINT,
    product_id BIGINT,
    service_id BIGINT,
    amount     DOUBLE PRECISION                        NOT NULL,
    currency   VARCHAR(255),
    CONSTRAINT pk_purchase PRIMARY KEY (id)
);

CREATE TABLE report
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reported_user_id BIGINT,
    user_id          BIGINT,
    report_message   VARCHAR(255),
    created_date     TIMESTAMP WITHOUT TIME ZONE,
    is_viewed        BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_report PRIMARY KEY (id)
);

CREATE TABLE service
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(255)                            NOT NULL,
    description           VARCHAR(255),
    price                 DOUBLE PRECISION                        NOT NULL,
    discount              DOUBLE PRECISION                        NOT NULL,
    is_visible            BOOLEAN                                 NOT NULL,
    is_available          BOOLEAN                                 NOT NULL,
    status                SMALLINT,
    offering_category_id  BIGINT,
    specifics             VARCHAR(255),
    duration              INTEGER                                 NOT NULL,
    reservation_deadline  INTEGER                                 NOT NULL,
    cancellation_deadline INTEGER                                 NOT NULL,
    reservation_type      VARCHAR(255),
    CONSTRAINT pk_service PRIMARY KEY (id)
);

CREATE TABLE service_event_type
(
    service_id    BIGINT NOT NULL,
    event_type_id BIGINT NOT NULL
);

CREATE TABLE service_images
(
    service_id BIGINT NOT NULL,
    images_url VARCHAR(255)
);

CREATE TABLE "user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE budget_item
    ADD CONSTRAINT FK_BUDGETITEM_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_EVENTTYPE FOREIGN KEY (event_type_id) REFERENCES event_types (id);

ALTER TABLE offering_review
    ADD CONSTRAINT FK_OFFERINGREVIEW_ON_PURCHASE FOREIGN KEY (purchase_id) REFERENCES purchase (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_OFFERINGCATEGORY FOREIGN KEY (offering_category_id) REFERENCES offering_type (id);

ALTER TABLE purchase
    ADD CONSTRAINT FK_PURCHASE_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE purchase
    ADD CONSTRAINT FK_PURCHASE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE purchase
    ADD CONSTRAINT FK_PURCHASE_ON_SERVICE FOREIGN KEY (service_id) REFERENCES service (id);

ALTER TABLE report
    ADD CONSTRAINT FK_REPORT_ON_REPORTEDUSER FOREIGN KEY (reported_user_id) REFERENCES "user" (id);

ALTER TABLE report
    ADD CONSTRAINT FK_REPORT_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE service
    ADD CONSTRAINT FK_SERVICE_ON_OFFERINGCATEGORY FOREIGN KEY (offering_category_id) REFERENCES offering_type (id);

ALTER TABLE favorite_products
    ADD CONSTRAINT fk_favpro_on_product FOREIGN KEY (favorite_products_id) REFERENCES product (id);

ALTER TABLE favorite_products
    ADD CONSTRAINT fk_favpro_on_user FOREIGN KEY (users_id) REFERENCES "user" (id);

ALTER TABLE favorite_services
    ADD CONSTRAINT fk_favser_on_service FOREIGN KEY (favorite_services_id) REFERENCES service (id);

ALTER TABLE favorite_services
    ADD CONSTRAINT fk_favser_on_user FOREIGN KEY (users_id) REFERENCES "user" (id);

ALTER TABLE product_event_type
    ADD CONSTRAINT fk_proevetyp_on_event_type FOREIGN KEY (event_type_id) REFERENCES event_types (id);

ALTER TABLE product_event_type
    ADD CONSTRAINT fk_proevetyp_on_product FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE service_event_type
    ADD CONSTRAINT fk_serevetyp_on_event_type FOREIGN KEY (event_type_id) REFERENCES event_types (id);

ALTER TABLE service_event_type
    ADD CONSTRAINT fk_serevetyp_on_service FOREIGN KEY (service_id) REFERENCES service (id);

ALTER TABLE service_images
    ADD CONSTRAINT fk_service_images_on_service FOREIGN KEY (service_id) REFERENCES service (id);