CREATE TABLE favorite_services
(
    favorite_offerings_id BIGINT NOT NULL,
    users_id              BIGINT NOT NULL
);

CREATE TABLE "user"
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE favorite_services
    ADD CONSTRAINT fk_favser_on_service FOREIGN KEY (favorite_offerings_id) REFERENCES service (id);

ALTER TABLE favorite_services
    ADD CONSTRAINT fk_favser_on_user FOREIGN KEY (users_id) REFERENCES "user" (id);